on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Clone element
        run: "git clone https://github.com/element-hq/element-web/"
      - name: Install deps
        run: "cd element-web && yarn install"
      - name: Create config
        run: "cd element-web && cp config.sample.json config.json"
