on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Clone element
        run: "git clone https://github.com/element-hq/element-web/"
      - name: Install deps
        run: |
            cd element-web
            yarn install
      - name: Create config
        run: |
            cd element-web
            echo '{
                "default_server_config": {
                    "m.homeserver": {
                        "base_url": "https://matrix-client.matrix.org",
                        "server_name": "matrix.org"
                    },
                    "m.identity_server": {
                        "base_url": "https://vector.im"
                    }
                },
                "disable_custom_urls": false,
                "disable_guests": false,
                "disable_login_language_selector": false,
                "disable_3pid_login": false,
                "brand": "SmasnugChat",
                "integrations_ui_url": "https://scalar.vector.im/",
                "integrations_rest_url": "https://scalar.vector.im/api",
                "integrations_widgets_urls": [
                    "https://scalar.vector.im/_matrix/integrations/v1",
                    "https://scalar.vector.im/api",
                    "https://scalar-staging.vector.im/_matrix/integrations/v1",
                    "https://scalar-staging.vector.im/api",
                    "https://scalar-staging.riot.im/scalar/api"
                ],
                "default_country_code": "GB",
                "show_labs_settings": true,
                "features": {},
                "default_federate": true,
                "default_theme": "dark",
                "room_directory": {
                    "servers": ["matrix.org"]
                },
                "enable_presence_by_hs_url": {
                    "https://matrix.org": false,
                    "https://matrix-client.matrix.org": false
                },
                "setting_defaults": {
                    "breadcrumbs": true
                },
                "jitsi": {
                    "preferred_domain": "meet.element.io"
                },
                "element_call": {
                    "url": "https://call.element.io",
                    "participant_limit": 8,
                    "brand": "Smasnug Call"
                },
                "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
            }' > config.json

      - name: Build
        run: |
            cd element-web
            yarn dist
      - name: Remove old
        run: |
            rm -rf docs
      - name: Deploy
        run: |
            tar -xvzf element-web/dist/*.tar.gz
            mv element-v* docs
      - name: Cleanup
        run: |
            rm -rf element-web
      - name: Push
        run: |
            git config user.name github-actions
            git config user.email email@email.com
            git add --all
            git commit -m "Automatic deploy"
            git push
